### ISSUE TITLE
¿Qué es una fecha de nacimiento?

### ISSUE THREAD

**Issue by Morad02** [MarioGuisado/TrainMe#10]
En #7 necesitamos saber en qué consiste una fecha de nacimiento. La fecha de nacimiento nos indica la fecha en que ha nacido el atleta. Hemos de tener en cuenta que para la lógica de negocio solo no es necesario el año en que ha nacido el atleta.

**Comment by JJ** [comment]
Esto no plantea un problema, ni está relacionado con ninguna historia de usuario. Todos los issues tienen que tener esas características, si no es imposible saber si se está haciendo algo bien o no.
