### ISSUE TITLE
Lenguaje de programación

### ISSUE THREAD

**Issue by Morad02** [MarioGuisado/TrainMe#5]
Hola, se me ha asignado este repositorio para el objetivo 2. Antes que nada, hay que decidir que lenguaje se va a utilizar. Teniendo en cuenta lo explicado en clase por el profesor, yo creo que estaría bien usar TypeScript o Go

**Comment by MarioGuisado** [comment]
¿Por qué crees que TypeScript es mejor opción a Java? Ambos permiten definir interfaces y son muy parecidos.

**Comment by Morad02** [comment]
Por ejemplo, TypeScript es tanto para backend como para fronted, mientras que Java no. Otra ventaja es que TypeScript presenta mayores facilidades para realizar testeo

**Comment by MarioGuisado** [comment]
Ok, nos quedamos con TypeScript.
