### ISSUE TITLE
¿Qué es un atleta?

### ISSUE THREAD

**Issue by Morad02** [MarioGuisado/TrainMe#7]
Para poder resolver #2  no hace falta saber qué es un atleta. 
Un atleta tiene la siguiente información:

Fecha de nacimiento
Nivel de rendimiento
Nivel de compromiso
Modalidad de entreno preferida
Preferencia contacto
Disponibilidad horaria semanal
Categoría de peso a la que pertenece

**Comment by MarioGuisado** [comment]
Es un dato que determina si ese entrenador tiene en ese momento plazas disponibles, y por lo tanto puede ser candidato para sugerirselo a atletas, o si por lo contrario no tiene plazas y debe ser excluído.

**Comment by Morad02** [comment]
Los objetos valores del problema son atletas y entrenadores
