### ISSUE TITLE
¿Qué es un entrenador?

### ISSUE THREAD

**Issue by Morad02** [MarioGuisado/TrainMe#8]
Para poder resolver #2  debemos saber qué es un entrenador. 
Los entrenadores buscan a atletas teniendo en cuenta estos parámetros:

Rango de edad
Nivel de rendimiento 
Nivel de compromiso
Modalidad de entreno preferida
Preferencia contacto
Disponibilidad horaria semanal del atleta
Categoría de peso a la que pertenece el atleta

**Comment by MarioGuisado** [comment]
La frecuencia en las comunicaciones indica la cantidad de feedback semanal del atleta al entrenador, y de comentarios del entrenador al atleta. La disponibilidad indica cuando ese entrenador o atleta puede comunicarse con el otro. Hay entrenadores que pueden tener una alta disponibilidad, y responder al atleta ante cualquier duda que le surja en un horario muy amplio, pero tener una frecuencia de comunicación baja con el atleta puesto que no requieren de un feedback constante del mismo. En general tanto frecuencia como disponibilidad podrían encontrarse en el rango [bajo, medio, alto].
